import Notification from "./components/Notification";
import "./globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "food-delivery-app",
  description: "food delivery app generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <div>
          <Notification />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
