import Notification from "./components/Notification";
import "./globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AuthProvider from "@/app/components/AuthProvider";
import React from "react";

const figtree: Nextfont = Figtree({ subsets: ["latin"], weight: ['400', '600', '800'] });

export const metadata: Metadata = {
  title: "food-delivery-app",
  description: "food delivery app generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={figtree.className}>
      <AuthProvider>
        <div>
          <Notification />
          <Navbar />
          {children}
          <Footer />
        </div>
      </AuthProvider>
      </body>
    </html>
  );
}
